### ISSUE TITLE
Error parsing text frame

### ISSUE THREAD

**Issue by martinb3** [gilbertw1/slack-scala-client#19]
Hi there -- at some point after a recent Slack update, I started seeing this constantly. Any clues as to what's going on there? Seems like it's happening at some regular interval.

```
[ERROR] [02/18/2016 16:16:06.542] [org_mbs3_trivial-akka.actor.default-dispatcher-2] [akka://org_mbs3_trivial/user/$a] [SlackRtmClient] Error parsing text frame
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(Invalid type property: {},WrappedArray(reconnect_url))))))
	at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67)
	at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:77)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsValue$class.as(JsValue.scala:65)
	at play.api.libs.json.JsObject.as(JsValue.scala:166)
	at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1.applyOrElse(SlackRtmClient.scala:103)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at slack.rtm.SlackRtmConnectionActor.aroundReceive(SlackRtmClient.scala:87)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525)
	at akka.actor.ActorCell.invoke(ActorCell.scala:494)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by gilbertw1** [comment]
I'll take a look!

**Comment by gilbertw1** [comment]
https://api.slack.com/events/reconnect_url

Looks like it's currently experimental and has no properties associated with it. No idea why they're actually sending it out now (or if it currently has a meaningful purpose). I'll do a little testing and see if they're actually sending data along with the event....at the very least I'll add support for parsing the event so you won't see errors whenever it comes in.

**Comment by martinb3** [comment]
Thanks for responding so quickly! I need to really dive in and help fix stuff w/ a PR instead of just filing issues :)

**Comment by gilbertw1** [comment]
No worries! I just pushed a commit to properly parse this event type. Interestingly it was sending down a websocket url in the event payload.

My guess is that at some point in the future they're start requiring clients to reconnect when this event is received. I'd imagine this is so they could force clients to disconnect / reconnect in the event of server upgrades, maintenance, load balancing, etc.

**Comment by martinb3** [comment]
Weeeeird. Thanks so much!
