### ISSUE TITLE
Could not initialise SlackRtmClient, errors out with TimeoutException

### ISSUE THREAD

**Issue by prayagupd** [gilbertw1/slack-scala-client#42]
I get following error while tryign to send a message to a channel, 

```bash
/api/rtm.start
[WARN] [01/12/2017 03:31:22.477] [slack-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(slack)] Illegal response header: Illegal 'expires' header: Illegal weekday in date 1997-07-26T05:00:00: is 'Mon' but should be 'Sat'
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:123)
	at slack.api.BlockingSlackApiClient.resolve(BlockingSlackApiClient.scala:366)
	at slack.api.BlockingSlackApiClient.startRealTimeMessageSession(BlockingSlackApiClient.scala:294)
	at slack.rtm.SlackRtmClient.<init>(SlackRtmClient.scala:31)
	at slack.rtm.SlackRtmClient$.apply(SlackRtmClient.scala:22)
	at com.flume.channel.EventNotifier$.doSomething(EventNotifier.scala:22)
	at com.flume.channel.EventNotifier$.main(EventNotifier.scala:35)
	at com.flume.channel.EventNotifier.main(EventNotifier.scala)
```

My code to send a message is, 

```scala
package com.flume.channel

import akka.actor.ActorSystem
import com.typesafe.config.ConfigFactory
import slack.rtm.SlackRtmClient

import scala.concurrent.ExecutionContext.Implicits.global
object EventNotifier {
  implicit val system = ActorSystem("slack")

  val config = ConfigFactory.load()
  val token = config.getString("api.key")

  def doSomething(): Unit = {
    val client = SlackRtmClient(token = token, duration = 5.seconds)
    val state = client.state

    val chanId = state.getChannelIdForName("test-bytecode").get
    client.sendMessage(chanId, "test-bytecode!")

    client.onMessage { message =>
      println(s"User: ${message.user}, Message: ${message.text}")
    }

  }

  def main(args: Array[String]): Unit = {
    doSomething()
  }
}

```

I could list the channels though, 

```scala
class Test {
  val config = ConfigFactory.load()
  val token = config.getString("api.key")
  val client = SlackApiClient(token)

  implicit val system = ActorSystem("slack")

  def main(args: Array[String]): Unit = {
    val res = client.listChannels()

    Thread.sleep(1000)

    res.onComplete {
      case Success(channels) =>  {
        println(channels)
      }
      case Failure(err) => {
        println(err)
      }
    }
  }
}
```

sbt
------

```
scalaVersion := "2.12.1"

libraryDependencies += "com.github.gilbertw1" %% "slack-scala-client" % "0.2.0"

libraryDependencies += "com.typesafe" % "config" % "1.3.1"

```

**Comment by martinb3** [comment]
I'm stuck on this as well.

**Comment by prayagupd** [comment]
@martinb3 I ended up using [scala-slack](https://github.com/flyberry-capital/scala-slack#usage), (`scala-check` is inactive since 2015, but solved my problem :) )

**Comment by gilbertw1** [comment]
Hi, thanks for reporting this! Have you tried increasing the timeout?

    SlackRtmClient(token, 10.seconds)

I'm wondering if it's a network latency issue, however I don't think that'd be the case if you could successfully list channels.

**Comment by martinb3** [comment]
Howdy! I get stuck on this:
```
**Illegal 'expires' header: Illegal weekday in date 1997-07-26T05:00:00: is 'Mon' but should be 'Sat'**
```

I waited a long time, but this error hung all the threads involved in delivering messages to actors.

**Comment by gilbertw1** [comment]
Hey, that isn't actually a fatal error, it's just a warning that gets logged by Akka http (it can be disabled in the Akka configuration). You'll probably notice that warning on any successful requests as well.

It seems as though the underlying cause is a timeout waiting on a response from the slack API, however I can't be 100% certain that's the case or not. That's why I was wondering if increasing the timeout would produce any results.

**Comment by martinb3** [comment]
Hi @gilbertw1 -- I'll open a different issue then; mine's definitely stuck, but it emits a different error after the warning RE: illegal headers.
