### ISSUE TITLE
Error when receiving warning for posting repeated URLs

### ISSUE THREAD

**Issue by nlw0** [gilbertw1/slack-scala-client#51]
I am making a bot that posts news articles links. This error message appears when a repeated url is posted, and Slack answers with a warning that the url was already posted recently so it will not be unfurled. It appears the client is having some trouble reading this answer...

```
Reply(true,3,1489849746.181580,<https://yro.slashdot.org/story/17/03/18/0047226/us-lawmakers-propose-minimum-seat-sizes-for-airlines?utm_source=rss1.0mainlinkanon&amp;utm_medium=feed>)
[ERROR] [03/18/2017 16:09:02.092] [slack-akka.actor.default-dispatcher-3] [akka://slack/user/$a] [SlackRtmClient] Error reading event: {"text":"Pssst! I didn’t unfurl <https://yro.slashdot.org/story/17/03/18/0047226/us-lawmakers-propose-minimum-seat-sizes-for-airlines?utm_source=rss1.0mainlinkanon&amp;utm_medium=feed> because it was already shared in this channel quite recently (within the last hour) and I didn’t want to clutter things up.","is_ephemeral":true,"username":"slackbot","type":"message","subtype":"bot_message","channel":"C4L6FFMJQ","ts":"1489849746.000000","msg":{"do_not_unfurl_links":true},"event_ts":"1489849746.848473"}
play.api.libs.json.JsResultException: JsResultException(errors:List((/bot_id,List(JsonValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:23)
	at play.api.libs.json.JsResult.fold(JsResult.scala:67)
	at play.api.libs.json.JsResult.fold$(JsResult.scala:65)
	at play.api.libs.json.JsError.fold(JsResult.scala:12)
	at play.api.libs.json.JsReadable.as(JsReadable.scala:22)
	at play.api.libs.json.JsReadable.as$(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:92)
	at slack.models.package$$anon$5.reads(package.scala:259)
	at play.api.libs.json.JsValue.validate(JsValue.scala:16)
	at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
	at play.api.libs.json.JsObject.validate(JsValue.scala:92)
	at play.api.libs.json.JsReadable.as(JsReadable.scala:21)
	at play.api.libs.json.JsReadable.as$(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:92)
	at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1.$anonfun$applyOrElse$1(SlackRtmClient.scala:112)
	at scala.util.Try$.apply(Try.scala:209)
	at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1.applyOrElse(SlackRtmClient.scala:112)
	at akka.actor.Actor.aroundReceive(Actor.scala:497)
	at akka.actor.Actor.aroundReceive$(Actor.scala:495)
	at slack.rtm.SlackRtmConnectionActor.aroundReceive(SlackRtmClient.scala:95)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by nlw0** [comment]
Another error today, I suppose it relates to reading JSON responses?...

```
[ERROR] [03/24/2017 09:24:54.745] [slack-akka.actor.default-dispatcher-2] [akka://slack/user/$a] [SlackRtmClient] Error reading event: {"type":"member_joined_channel","user":"U4JHAUWKB","channel":"C1NRQ1QQG","channel_type":"C","event_ts":"1490343904.750020","ts":"1490343904.750020"}
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List(Invalid type property: {}),WrappedArray(member_joined_channel))))))
        at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:23)
        at play.api.libs.json.JsResult.fold(JsResult.scala:67)
        at play.api.libs.json.JsResult.fold$(JsResult.scala:65)
        at play.api.libs.json.JsError.fold(JsResult.scala:12)
        at play.api.libs.json.JsReadable.as(JsReadable.scala:22)
        at play.api.libs.json.JsReadable.as$(JsReadable.scala:21)
        at play.api.libs.json.JsObject.as(JsValue.scala:92)
        at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1.$anonfun$applyOrElse$1(SlackRtmClient.scala:112)
        at scala.util.Try$.apply(Try.scala:209)
        at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1.applyOrElse(SlackRtmClient.scala:112)
        at akka.actor.Actor.aroundReceive(Actor.scala:497)
        at akka.actor.Actor.aroundReceive$(Actor.scala:495)
        at slack.rtm.SlackRtmConnectionActor.aroundReceive(SlackRtmClient.scala:95)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by gilbertw1** [comment]
There are a few newly added message types that I haven't gotten around to supporting.

It looks there is an issue with:
* member_joined_channel
* bot_message

I'm aware of the bot_message issue and will be adding support for that type shortly. Thanks for reporting!
