### ISSUE TITLE
A certain exception can cause events to be published twice

### ISSUE THREAD

**Issue by erikedin** [gilbertw1/slack-scala-client#55]
I had an issue with events being published twice. That is, the `onMessage` callback was called twice for each message.
Below is a partial explanation of what the issue is.

Short version: Sometimes an exception is thrown in `SlackRtmConnectionActor.connectWebSocket()` which causes a new `WebSocketClientActor` to be created, even though the connection actually succeeded for the first, meaning that there are now two `WebSocketClientActor`s.

Longer version: For whatever reason, the WebSockets to Slack seem to go down every now and then. From my experience with Slack this is probably normal, and not an issue with this library. Looking at the logs, the double events started happening after this exception:

```
[INFO] [05/30/2017 08:53:57.174] [slack-akka.actor.default-dispatcher-7] [akka://slack/user/$a] [SlackRtmConnectionActor] Starting web socket client
[INFO] [05/30/2017 08:53:57.182] [slack-akka.actor.default-dispatcher-5] [akka://slack/user/$g] WebSocketClientActor] Connecting to RTM: wss://mpmulti-wot1.slack-msgs.com/websocket/mf0mrmcCftZH3dyRtkx1w389QwuJcIBRYD-GiV5GU4Y6oo6PSzNKp_vNewriKysFkQlt6A1PXoLsszthWVLDc_L5Nw7oIbQjqbTHehTR0lrCrNvQ4yhUvw3gwK4TgZrcHDxHQD8T0M-XyzCFbtJGtFkjmdb8zClGaHtkX766xaY=
[INFO] [05/30/2017 08:53:58.888] [slack-akka.actor.default-dispatcher-10] [akka://slack/user/$g] [WebSocketClientActor] Web socket connection success
Event: Hello(hello)
[ERROR] [05/30/2017 08:54:10.443] [slack-akka.actor.default-dispatcher-7] [akka://slack/user/$a] Caught exception trying to connect websocket
java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 10 seconds while still waiting for outstanding data
	at akka.http.impl.util.ToStrict$$anon$2.onTimer(package.scala:143)
	at akka.stream.stage.TimerGraphStageLogic.onInternalTimer(GraphStage.scala:1152)
	at akka.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1(GraphStage.scala:1141)
	at akka.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1$adapted(GraphStage.scala:1141)
	at akka.stream.stage.TimerGraphStageLogic$$Lambda$1071/799669.apply(Unknown Source)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:691)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:419)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor.aroundReceive(Actor.scala:484)
	at akka.actor.Actor.aroundReceive$(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[INFO] [05/30/2017 08:54:10.445] [slack-akka.actor.default-dispatcher-7] [akka://slack/user/$a] [SlackRtmConnectionActor] WebSocket Client successfully connected
```

(The `Event: Hello(hello)` is a debug print of my own, in my bot, so this indicates that the event was actually processed.)

Note that the id of the `WebSocketClientActor` is `akka://slack/usr/$g`. Looking at the timestamps it logs 
`Web socket connection success` at 08:53:58. This indicates that the HTTP WebSocket upgrade was completed, and is from [this line 98](https://github.com/gilbertw1/slack-scala-client/blob/master/src/main/scala/slack/rtm/WebSocketClientActor.scala#L98).
This will be followed immediately by the actor sending a message `WebSocketConnectSuccess` to itself. This will in turn lead to it sending the message `WebSocketClientConnected` to the `SlackRtmConnectionActor`. When receiving this message the `SlackRtmConnectionActor` will log `WebSocket Client successfully connected` on [line 144](https://github.com/gilbertw1/slack-scala-client/blob/master/src/main/scala/slack/rtm/SlackRtmClient.scala#L144).
However, note that this log appears nearly 12 seconds later at 08:54:10. In the mean time a `TimeoutException` is thrown and caught in `SlackRtmConnectionActor.connectWebSocket()`. 

Unfortunately I'm still not clear on where or why that exception is thrown, why it is caught in `connectWebSocket()`, or how the actor is still running. However, it's fairly clear that the WebSocket with id `$g` is in fact operational. Because the exception is thrown, the `SlackRtmConnectionActor` sends the message `WebSocketClientConnectFailed` to itself, because it assumes the connection was unsuccessful. A hand-wavy guess is that since it connects the WebSocket in `preStart()`, the timeout blocks the start of the `WebSocketConnectionActor`, so that incoming or outgoing messages are queued, until the exception is thrown and the actor starts completely. Or, it's the `SlackRtmConnectionActor` which is blocked, and can't receive messages. I'm not good enough at Akka to say if that makes sense. Does maybe `preStart()` happen in the thread that creates the actor? In that case, maybe it's the line https://github.com/gilbertw1/slack-scala-client/blob/master/src/main/scala/slack/rtm/WebSocketClientActor.scala#L94
that blocks the `SlackRtmConnectionActor`.

Anyhow, this exception leads to the `SlackRtmConnectionActor` calling `connectWebSocket()` again, after a one second timeout, like the following logs show

```
[INFO] [05/30/2017 08:54:10.469] [slack-akka.actor.default-dispatcher-7] [akka://slack/user/$a] [SlackRtmConnectionActor] WebSocket Client failed to connect, retrying in 1 seconds
[INFO] [05/30/2017 08:54:11.492] [slack-akka.actor.default-dispatcher-3] [akka://slack/user/$a] [SlackRtmConnectionActor] Starting web socket client
[WARN] [05/30/2017 08:54:16.058] [slack-akka.actor.default-dispatcher-13] [akka.actor.ActorSystemImpl(slack)] Illegal response header: Illegal 'expires' header: Illegal weekday in date 1997-07-26T05:00:00: is 'Mon' but should be 'Sat'
[INFO] [05/30/2017 08:54:26.670] [slack-akka.actor.default-dispatcher-11] [akka://slack/user/$h] WebSocketClientActor] Connecting to RTM: wss://mpmulti-7ty2.slack-msgs.com/websocket/FYtGj8xE_pC3CtCUaeTOcEm8XJ_7VWupE1vehrVCWR8IuS2VVvYVLEwzjpXtRVt9OGcYWMpyzYmh2LM7BmFn0WMb4ufnkDB0sfuGuHX2vPXm6t0rHpSCLwMUfVrqjntpYsbwxP4r0tnybS0i9fH5Bk1DCGgKx0sxLBR-0qs7IDM=
[INFO] [05/30/2017 08:54:28.350] [slack-akka.actor.default-dispatcher-7] [akka://slack/user/$h] [WebSocketClientActor] Web socket connection success
[INFO] [05/30/2017 08:54:28.351] [slack-akka.actor.default-dispatcher-7] [akka://slack/user/$a] [SlackRtmConnectionActor] WebSocket Client successfully connected
Event: Hello(hello)
```

So, the end result is that because the exception is thrown even though the connection was a success, another actor, this time with id `akka://slack/user/$h`, is created, and we get two WebSocket connections, both delivering events.

Note that this happens on my Raspberry Pi 3, so it's entirely possible that this happens only on low-end hardware. I can't say for sure, but it appears this happens mostly for specific teams. I have one test team with only one real user, and I haven't reproduced it there. I have only seen it on my main Slack team with 20+ users. This could be coincidence, or it could be that my main team causes more data to be sent to the Slack bot, causing this error more often.

**Comment by asheshambasta** [comment]
Same issue here.

**Comment by gilbertw1** [comment]
Hey guys, sorry for the long delay on replying to this issue. 

I've had a chance to review the problem and I believe what was happening was that the `WebSocketClientActor` was encountering an exception and was being restarted by the default supervisor strategy. On restart, it was failing to connect and subsequently notified the `SlackRtmConnectionActor` of the failure to connect. After this point the `SlackRtmConnectionActor` would attempt to reconnect by creating a new websocket connection (and actor) going forward. Unfortunately this left the old `WebSocketClientActor` running, who I can only assume attempted to continue processing his mailbox, hit another exception, and restarted to successfully reconnect to the Slack Rtm.

The above scenario reveals the complexity of the current websocket failure handling logic, most of which is carry over from the old implementation that was on top of spray-websocket. As such, I've simplified this logic and (I believe) removed this bug in the process in a66ccb5cf8e8b7e0f9ce8a4b97b1c9c968aa16a5.

I'll be releasing this pretty soon after doing some additional testing in version `0.2.3`. I'll put an additional comment here when it's released. If you could let me know whether or not this resolves your problem, I'd appreciate it.

**Comment by gilbertw1** [comment]
Also, thanks for the incredibly detailed bug description!
