### ISSUE TITLE
java.lang.NoSuchMethodError while trying to initialize

### ISSUE THREAD

**Issue by idoshamun** [gilbertw1/slack-scala-client#59]
Any reason why this could happen?

Using Akka 2.5.4, also tried 2.4.14 but none of it works

```scala
val config: Config = ConfigFactory.load()
val token: String = config.getString("slack.bot.token")
val client = SlackApiClient(token)
```
```
Exception in thread "main" java.lang.NoSuchMethodError: play.api.libs.json.JsonConfiguration$.defaultConfiguration()Lplay/api/libs/json/JsonConfiguration;
	at slack.api.SlackApiClient$.<init>(SlackApiClient.scala:20)
	at slack.api.SlackApiClient$.<clinit>(SlackApiClient.scala)
	at Boot$.delayedEndpoint$com$cryptoknight$Boot$1(Boot.scala:26)
	at Boot$delayedInit$body.apply(Boot.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
```

**Comment by idoshamun** [comment]
After some investigation I realized that it has to do with installing play ws standalone.
If I remove those two lines everything works:
```
"com.typesafe.play" %% "play-ahc-ws-standalone" % wsVersion,
  "com.typesafe.play" %% "play-ws-standalone-json" % wsVersion,
```

**Comment by gilbertw1** [comment]
Yep, I'm guessing this is caused specifically by the conflicting version of `play-json` being included. You should be able to use `slack-scala-client` with `play-ws` if you use the current play version: 2.6.

**Comment by idoshamun** [comment]
I am using the standalone version of ws and it is indeed the newest version
2.6.3. Also tried other versions as well, but it didn't work.

**Comment by gilbertw1** [comment]
Actually, it's been a while since I've pushed a release to maven central, and I believe that the last release was using a milestone play version: `2.6.0-M1`. This might be the cause of the problem. I just merged a few pull requests and updated all of the project dependencies, including `play-json`. I'll do a little testing to verify that the updated dependency fixes the problem, and push a new version out to maven central.

**Comment by idoshamun** [comment]
Amazing! waiting for it

**Comment by gilbertw1** [comment]
Hey, I just pushed the a 0.2.2 release to maven central. It should be available in the next few hours.

**Comment by gilbertw1** [comment]
@idoshamun Have you had a chance to check if the 0.2.2 release fixes your problem?

**Comment by idoshamun** [comment]
Sorry I totally forgot, will try to get to it soon, thanks! :)

**Comment by idoshamun** [comment]
Works even with `wsVersion=1.1.1`
