### ISSUE TITLE
getImHistory: JsResultException has occurred

### ISSUE THREAD

**Issue by itohjam** [gilbertw1/slack-scala-client#7]
I call the `SlackApiClient.getImHistory`, then the following exception has occurred.
I think it is caused by the difference between the type of `HistoryChunk.latest` and `latest` of API response (`HistoryChunk.latest`: Long, API response `latest`: String).

```
play.api.libs.json.JsResultException: JsResultException(errors:List((/latest,List(ValidationError(error.expected.jsnumber,WrappedArray())))))
        at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67)
        at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67)
        at play.api.libs.json.JsResult$class.fold(JsResult.scala:77)
        at play.api.libs.json.JsError.fold(JsResult.scala:13)
        at play.api.libs.json.JsValue$class.as(JsValue.scala:65)
        at play.api.libs.json.JsObject.as(JsValue.scala:166)
        at slack.api.SlackApiClient$$anonfun$getImHistory$1.apply(SlackApiClient.scala:381)
        at slack.api.SlackApiClient$$anonfun$getImHistory$1.apply(SlackApiClient.scala:381)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:236)
        at scala.util.Try$.apply(Try.scala:191)
        at scala.util.Success.map(Try.scala:236)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

code:
```scala
val apiClient = SlackApiClient(token)
val ftHist = apiClient.getImHistory(
    channelId = channelId,
    latest = Some(100000000000000L),
    oldest = Some(0L),
    inclusive = Some(0),
    count = Some(10)
)
val history: HistoryChunk = Await.result(ftHist, 10.second)
println(history)
```

**Comment by gilbertw1** [comment]
Thanks for the bug report! 

I've just pushed a commit to fix this issue. Two things to note:

1) 'latest' is now an ```Option[String]``` as it's elided completely from the response if latest isn't passed in
2) the 'latest' and 'oldest' parameters are now ```Option[String]``` values as well to match Slack's types
